### ISSUE TITLE
Request to transfer control of all of my Minetest-related repositories

### ISSUE THREAD

**Issue by VanessaE** [mt-mods/mt-mods#1]
I have decided to basically retire from most Minetest-related activities, which includes modding.

Since a lot of people rely on them, I'd like to hand-over ownership and maintenance of any or all of my Minetest-related projects hosted on my Gitlab account to someone else.  Obviously that'll require cloning them all from there to here.

This issue has been crossposted to minetest-mods and mt-mods -- the idea here is that I'm perfectly happy for either of these organizations to get my mods, just whoever wants to take on which ones.  In fact, if others outside these groups wish to take over some projects, I'm okay with that, too.

~~All of my projects are located at https://gitlab.com/users/VanessaE/projects~~

Although it's conceivable that I'll randomly find a reason to add/change something in one of my projects, I do not require commit access or anything of the kind.  That stuff can be done with ordinary pull requests.

All of the following projects need to be transferred somewhere:

**Mods**
- [X] https://gitlab.com/VanessaE/pipeworks
- [x] https://gitlab.com/VanessaE/signs_lib
- [x] https://gitlab.com/VanessaE/basic_signs
- [x] https://gitlab.com/VanessaE/street_signs
- [x] https://gitlab.com/VanessaE/homedecor_modpack
- [x] https://gitlab.com/VanessaE/home_workshop_modpack
- [x] https://gitlab.com/VanessaE/biome_lib
- [x] https://gitlab.com/VanessaE/plantlife_modpack
- [x] https://gitlab.com/VanessaE/moretrees
- [x] https://gitlab.com/VanessaE/minislots
- [x] https://gitlab.com/VanessaE/basic_materials
- [x] https://gitlab.com/VanessaE/unifieddyes
- [x] https://gitlab.com/VanessaE/autoclose_doors
- [x] https://gitlab.com/VanessaE/reboot_warner
- [x] https://gitlab.com/VanessaE/coloredwood
- [x] https://gitlab.com/VanessaE/led_marquee
- [x] https://gitlab.com/VanessaE/nixie_tubes
- [x] https://gitlab.com/VanessaE/simple_streetlights
- [x] https://gitlab.com/VanessaE/round_trunks

**Texture packs**
- [x] https://gitlab.com/VanessaE/hdx-64
- [x] https://gitlab.com/VanessaE/hdx-128
- [x] https://gitlab.com/VanessaE/hdx-256
- [x] https://gitlab.com/VanessaE/hdx-512
- [x] https://gitlab.com/VanessaE/c64-16px
- [x] https://gitlab.com/VanessaE/c64-64px

**Mod forks where I eventually became the maintainer**
- [x] https://gitlab.com/VanessaE/currency
- [x] https://gitlab.com/VanessaE/ilights
- [x] https://gitlab.com/VanessaE/gloopblocks
- [x] https://gitlab.com/VanessaE/steel

**RBA's old shader projects**
These shaders are unmodified from RBA's last changes, as far as I know, and probably don't work anymore, but they should still be copied over, for posterity:

- [x] https://gitlab.com/VanessaE/water_surface_shader
- [x] https://gitlab.com/VanessaE/shaded_lava
- [x] https://gitlab.com/VanessaE/lava_surface_shader
- [x] https://gitlab.com/VanessaE/water_shaders

Any open issues on the above repositories should be copied-over as well, though I don't know if there's any automated way to do that.

Any other projects found on my Gitlab profile are either outdated, or are just forks of other peoples' projects where I probably contributed something, or are unrelated to Minetest, and may be ignored.

All projects transferred to someone else will be deleted from my Gitlab account.

- [x]  ~~Once everything above has been transferred, I'll make one final release of Dreambuilder, and then it~~ Dreambuilder and its two side projects should also be transferred (https://gitlab.com/VanessaE/dreambuilder_game ~ https://gitlab.com/VanessaE/dreambuilder_themes ~ https://gitlab.com/VanessaE/dreambuilder_hotbar).

**Comment by S-S-X** [comment]
I guess at least basic_materials could fit well because of pipeworks and technic plus.
@BuckarooBanzay what do you think? Or was there some bigger plans...?

However that mod should stay as stable as possible but I guess ensuring that is something to discuss somewhere else (or separate issues for mods, I guess there's some work to do with adopted stuff anyway).

**Comment by S-S-X** [comment]
Well, I've pulled basic_materials to [mt-mods/basic_materials](https://github.com/mt-mods/basic_materials) with complete history, so waiting there for "semi-official" decision 😄

**Comment by BuckarooBanzay** [comment]
> Or was there some bigger plans...?

There is no "great plan" for all of this, but i'm writing an official "guideline" of the `mt-mods` org soon(-ish)
The main theme should be along the lines of "innovation, not mod-graveyard"

**Comment by OgelGames** [comment]
Out of the 26 mods (not counting the textures and old shaders), 13 of them are on pandorabox, so it would be in our interest to have them easily maintainable.

So if we're going to "take" half of them already, I see no reason not to take the other half too :)

The textures and old shaders probably don't fit in `mt-mods`, as those likely won't need much (or any) maintenance.

**Comment by wsor4035** [comment]
texturepacks could go to https://github.com/minetest-texture-packs

**Comment by wsor4035** [comment]
> texturepacks could go to https://github.com/minetest-texture-packs

@Panquesito7 thoughts?

**Comment by Panquesito7** [comment]
> > texturepacks could go to https://github.com/minetest-texture-packs
> 
> @Panquesito7 thoughts?

Sounds good 👍 CC: @tacotexmex.

**Comment by S-S-X** [comment]
I've pulled following repos to mt-mods (everything under _Mods_ header):
Check marks indicate that issues and merge requests have been added from original repo.
- [x] signs_lib
- [x] basic_signs
- [x] street_signs
- [x] biome_lib
- [x] plantlife_modpack
- [ ] moretrees
- [x] minislots
- [ ] unifieddyes
- [x] autoclose_doors
- [x] reboot_warner
- [x] coloredwood
- [x] led_marquee
- [x] nixie_tubes
- [x] round_trunks

Issues and merge requests have not been copied but I could take a look if those could also be copied all at once using API.
edit. Issues and merge requests have been copied for checked repos.

**Comment by S-S-X** [comment]
> Mod forks where I eventually became the maintainer

Some mods do contain questionable licenses:
* steel does not include any license at all.
* others do have licenses added (and/or changed) later but licensing/relicensing is _apparently_ not done by copyright holder.

If there's original sources for licenses / mentions of intended license by copyright owner it could be good to add notes about license sources to repositories.

Other than that I guess it could be assumed that licenses (where license exists) are valid, possibly released in some forum or otherwise authorized by copyright owner?
(also I did not go through all repos, just ones under mentioned header after I noticed that steel did not have license)

**Comment by OgelGames** [comment]
`steel` has the license in its readme, `reboot_warner` and `autoclose_doors` don't have a license though.

**Comment by VanessaE** [comment]
`reboot_warner` and `autoclose_doors` were one-offs for my servers, originally.  Consider them public domain ~~, or WTFPL~~ or CC0 if you like.

For the sake of being official, I've just pushed the CC0 license to those two.

As for licenses of the ones I "took over", your guesses are as good as mine. :wink:

`ilights` and `currency` were originally by Dan Duncombe.  Near as I can tell, he only ever uploaded his originals as ZIPs to his forum posts.  Those ZIPs can be found on these pages:

https://forum.minetest.net/viewtopic.php?f=16&t=7422
https://forum.minetest.net/viewtopic.php?f=13&t=7002

I'm 99% certain that the licenses declared on those posts are correct.

Gloopblocks was originally by Gloopmaster/Nekogloop.  The original repo for THAT one appears to be here: https://github.com/GloopMaster/gloopblocks

**Comment by VanessaE** [comment]
For the sake of being official, I've just pushed the CC0 license to those two.

**Comment by VanessaE** [comment]
As for licenses of the ones I "took over", your guesses are as good as mine. :wink:

ilights and currency were originally by Dan Duncombe.  Near as I can tell, he only ever uploaded his originals as ZIPs to his forum posts.  Those ZIPs can be found on these pages:

https://forum.minetest.net/viewtopic.php?f=16&t=7422
https://forum.minetest.net/viewtopic.php?f=13&t=7002

Gloopblocks was originally by Gloopmaster/Nekogloop.  The original repo for THAT one appears to be here: https://github.com/GloopMaster/gloopblocks

**Comment by VanessaE** [comment]
> Issues and merge requests have not been copied

Ok, let me know when I can delete my repos.

**Comment by wsor4035** [comment]
ok, all of the "Mod forks where I eventually became the maintainer" have been moved and issues for just that section moved

**Comment by S-S-X** [comment]
pipeworks and basic_materials were done among first mods.

I've moved/checked issues for some mods, check marks in comment: https://github.com/mt-mods/mt-mods/issues/1#issuecomment-981060757

@wsor4035 you've handled these too?
homedecor_modpack, home_workshop_modpack and simple_streetlights

If so then I think only things that still need some work would be:
* unifieddyes _issues and merge requests_
* moretrees _issues and merge requests_
* Texture packs _not for mt-mods_
* RBA's old shader projects _not for mt-mods_

**Comment by wsor4035** [comment]
"Mod forks where I eventually became the maintainer" and "homedecor_modpack, home_workshop_modpack and simple_streetlights" have all had there issues and pull requests moved

**Comment by wsor4035** [comment]
> pipeworks and basic_materials were done among first mods.
> 
> I've moved/checked issues for some mods, check marks in comment: [#1 (comment)](https://github.com/mt-mods/mt-mods/issues/1#issuecomment-981060757)
> 
> @wsor4035 you've handled these too? homedecor_modpack, home_workshop_modpack and simple_streetlights
> 
> If so then I think only things that still need some work would be:
> 
> * unifieddyes _issues and merge requests_
> * moretrees _issues and merge requests_
> * Texture packs _not for mt-mods_
> * RBA's old shader projects _not for mt-mods_

issues (no prs) moved

**Comment by VanessaE** [comment]
Oh, I also have a fork of Sanchez'  blox mod on my repo:
https://gitlab.com/VanessaE/blox
https://forum.minetest.net/viewtopic.php?t=1960

Something should be done with it also.  I do not consider myself to be the maintainer, but apparently my fork is the one people normally use, probably because I converted it to use hardware coloring through Unified Dyes.

**Comment by wsor4035** [comment]
@VanessaE https://github.com/mt-mods/blox done

**Comment by S-S-X** [comment]
> @VanessaE https://github.com/mt-mods/blox done

Anything useful in colored-itemstacks branch? 3 years ago updated, no conflicts with master.

**Comment by wsor4035** [comment]
its one commit ahead, 6 behind, anyways its on github if we want it, dont have time to read it over atm

**Comment by VanessaE** [comment]
I am not sure what that branch is actually for -- I could swear itemstacks already had color.

**Comment by VanessaE** [comment]
Ok, by my count, all issues/PRs that needed moved have been moved.  All mod repos have been deleted.

All that leaves is the texture packs and the shaders.

**Comment by tacotexmex** [comment]
> > > texturepacks could go to https://github.com/minetest-texture-packs
> 
> > 
> 
> > @Panquesito7 thoughts?
> 
> 
> 
> Sounds good 👍 CC: @tacotexmex.
> 
> 

What is the quality of these TPs?
