### ISSUE TITLE
update luacheck workflow

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/mt-mods#14]
shouldnt https://github.com/mt-mods/mt-mods/blob/master/snippets/luacheck.yml be updated to use https://github.com/lunarmodules/luacheck/pull/108

**Comment by wsor4035** [comment]
cc @BuckarooBanzay

**Comment by OgelGames** [comment]
No, that is a `.luacheckrc` config option, not part of the workflow file.

**Comment by S-S-X** [comment]
> No, that is a .luacheckrc config option, not part of the workflow file.

It depends, if it is made default through workflow file then it is not part of `.luacheckrc` but part of the workflow file. (well, it can be either or both depending on which outcome we'd like most)

**Comment by BuckarooBanzay** [comment]
`lunarmodules/luacheck@master` uses the latest luacheck version since a few weeks now (`latest` on their side doesn't mean latest luacheck in the action flow :shrug:) no need to change/update that :)

it feels much cleaner now: https://github.com/BuckarooBanzay/mapsync/blob/master/.luacheckrc

**Comment by S-S-X** [comment]
> it feels much cleaner now: https://github.com/BuckarooBanzay/mapsync/blob/master/.luacheckrc

Couldn't you also drop `"minetest",` from `globals`? Or is it still needed?

**Comment by BuckarooBanzay** [comment]
> Couldn't you also drop "minetest", from globals? Or is it still needed?

oh, right, that should work, of course :)

**EDIT**: err, no, it's a write-global, i think i'm modifiying a few fields on that
