### ISSUE TITLE
Pipeworks repositry adoption

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/mt-mods#2]
Just for discussion (and issue I noticed).

- [x] No tags in repository.
    Tags probably just were not pushed but hopefully someone still has these.
    Push tags from "somewhere"™

**Comment by BuckarooBanzay** [comment]
Yeah, forgot those :facepalm:
I pushed them a few minutes ago :+1:

**Comment by BuckarooBanzay** [comment]
Updated the links on cdb too: https://content.minetest.net/packages/VanessaE/pipeworks/
Closing this...
