### ISSUE TITLE
IRC Channel bridge

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/mt-mods#3]
Can be done on a "main" and "-offtopic" channel, not sure about the demand though

**Comment by Panquesito7** [comment]
Hey there! Contact me via Discord if you need any help. 🙂

**Comment by wsor4035** [comment]
can this be closed as the bridge is now operational?

**Comment by S-S-X** [comment]
> can this be closed as the bridge is now operational?

yeah I think so, just add issues/pull requests for config / mt-mods-infra repo to connect channels and change other things.
