### ISSUE TITLE
add cdb review feed channel on discord

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/mt-mods#9]
Inspired by Warr1024's `cdb2discord` here: https://gitlab.com/sztest/cdb2discord/-/blob/master/index.js

![Screenshot_2023-07-05_16-23-43](https://github.com/mt-mods/mt-mods/assets/39065740/f01617f6-8ed4-4173-88a9-63d07a3452c1)
Discord-link: https://discord.com/channels/507234450615042048/711949245510320139

I'd like to add either warr's package directly or roll my own bot to post contentdb releases of `mt-mods` packages to a channel in our discord.

could also be linked to irc, not sure how useful that is though

:+1: or :-1: appreciated

**Comment by wsor4035** [comment]
do we really need this since most of the stuff here is auto deployed to cdb, so it would mostly be a duplicate of commits?

**Comment by BuckarooBanzay** [comment]
> do we really need this since most of the stuff here is auto deployed to cdb, so it would mostly be a duplicate of commits?

fair point, closing this for now..

**Comment by Niklp09** [comment]
A bot/webhook which shows package reviews etc would be more useful...

**Comment by BuckarooBanzay** [comment]
> A bot/webhook which shows package reviews etc would be more useful...

hm, this sounds useful

**Comment by BuckarooBanzay** [comment]
this _should_ work now
